global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'harpia-api'
    static_configs:
      - targets: ['production_api_hs:4001']
    metrics_path: '/metrics'

  - job_name: 'harpia-proxysql'
    static_configs:
      - targets: ['proxysql_api_main_harpiasystem:6032']
    metrics_path: '/metrics'

  - job_name: 'harpia-redis'
    static_configs:
      - targets: ['redis_api_main_harpiasystem_dev:6379']
    metrics_path: '/metrics'

  - job_name: 'harpia-sentinel-api'
    static_configs:
      - targets: ['api_sentinel_harpiasystem_dev:7771']
    metrics_path: '/metrics'

  - job_name: 'harpia-sentinel-mariadb'
    static_configs:
      - targets: ['mariadb_sentinel:3306']
    metrics_path: '/metrics'

  - job_name: 'harpia-sentinel-redis'
    static_configs:
      - targets: ['redis_sentinel_dev:6379']
    metrics_path: '/metrics'

  - job_name: 'harpia-services'
    dns_sd_configs:
      - names:
        - 'tasks.*'
        type: 'A'
        port: 9090
    relabel_configs:
      - source_labels: [__meta_dns_name]
        regex: 'tasks\.(.+)'
        target_label: service 